matrix:
  include:
      - language: csharp  
        solution: DocxToHtmlView.sln
        mono: none
        dotnet: 3.1
        script:
            - dotnet restore
            - dotnet build -c Release            

      - language: node_js
        node_js:
            - 10
        script:
            - cd src/Presentation/Editor.Web/ClientApp
            - npm -v
            - npm install
            - npm run build